version: '3'

# volumes:
#   nextcloud:
#   db:

services:
  nextcloud_db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - cloudnet
    volumes:
      - ./nextcloud-db:/var/lib/mysql
    env_file:
        - .env

  nextcloud:
    image: nextcloud:24-apache
    restart: always
    networks:
      - cloudnet
    ports:
      - 8080:80
    volumes:
      - ./nextcloud-docroot:/var/www/html
    env_file:
        - .env

networks:
  cloudnet:
    name: cloudnet
    driver: bridge
